version: "3.5"

services:
  app:
    container_name: lynx-app
    build:
      context: ./
      dockerfile: Dockerfile
      target: local
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - nextjs-node-modules:/usr/src/app/node_modules

volumes:
  nextjs-node-modules: